#!/usr/bin/env python3
"""
Interactive 3D Voxeland Semantic Map Visualizer
Reads PLY files generated by Voxeland and displays an interactive 3D view
with geometric and semantic information.
"""

import numpy as np
import plotly.graph_objects as go
import argparse
import sys
from pathlib import Path
from collections import defaultdict


def read_ply_file(ply_path):
    """
    Reads a Voxeland PLY file with semantic information.
    
    Returns:
        dict with 'vertices' (numpy array Nx7: x,y,z,r,g,b,instance_id),
             'categories' (list of category names),
             and 'header_info' (file metadata)
    """
    print(f"Reading PLY file: {ply_path}")
    
    vertices = []
    categories = []
    header_lines = []
    reading_header = True
    
    with open(ply_path, 'r') as f:
        for line in f:
            line = line.strip()
            
            if reading_header:
                header_lines.append(line)
                if line.startswith('element vertex'):
                    vertex_count = int(line.split()[-1])
                if line == 'end_header':
                    reading_header = False
                continue
            
            # Parse vertex line: x y z r g b instance_id category
            parts = line.split()
            if len(parts) >= 8:
                x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
                r, g, b = int(parts[3]), int(parts[4]), int(parts[5])
                instance_id = int(parts[6])
                category = parts[7]
                
                vertices.append([x, y, z, r, g, b, instance_id])
                categories.append(category)
    
    vertices_array = np.array(vertices)
    print(f"✓ Read {len(vertices_array)} voxels")
    
    # Extract header information
    header_info = {}
    for line in header_lines:
        if line.startswith('comment'):
            header_info['comment'] = line.replace('comment ', '')
    
    return {
        'vertices': vertices_array,
        'categories': categories,
        'header_info': header_info
    }


def organize_by_instances(vertices, categories):
    """
    Organizes voxels by instance and category.
    
    Returns:
        dict: {instance_id: {'coords': array, 'colors': array, 'category': str, 'count': int}}
    """
    instances = defaultdict(lambda: {
        'coords': [],
        'colors': [],
        'category_counts': defaultdict(int),
        'count': 0
    })
    
    for i, vertex in enumerate(vertices):
        x, y, z, r, g, b, instance_id = vertex
        category = categories[i]
        
        instances[instance_id]['coords'].append([x, y, z])
        instances[instance_id]['colors'].append([r, g, b])
        instances[instance_id]['category_counts'][category] += 1
        instances[instance_id]['count'] += 1
    
    # Convert to numpy arrays and determine dominant category
    result = {}
    for instance_id, data in instances.items():
        coords = np.array(data['coords'])
        colors = np.array(data['colors'])
        
        # Dominant category
        dominant_category = max(data['category_counts'].items(), key=lambda x: x[1])[0]
        
        result[instance_id] = {
            'coords': coords,
            'colors': colors,
            'category': dominant_category,
            'count': data['count'],
            'category_counts': dict(data['category_counts'])
        }
    
    return result


def create_interactive_visualization(ply_data, output_html=None, show_unknown=True, 
                                     subsample_unknown=10, subsample_known=2):
    """
    Creates an interactive 3D visualization with Plotly.
    
    Args:
        ply_data: PLY data
        output_html: Path to save HTML output (optional)
        show_unknown: Whether to show "unknown" voxels
        subsample_unknown: Subsampling factor for unknown voxels (faster rendering)
        subsample_known: Subsampling factor for known categories
    """
    vertices = ply_data['vertices']
    categories = ply_data['categories']
    
    print("Organizing voxels by instances...")
    instances = organize_by_instances(vertices, categories)
    
    # Create figure
    fig = go.Figure()
    
    # Separate unknown and known instances
    unknown_instances = {k: v for k, v in instances.items() if v['category'] == 'unknown'}
    known_instances = {k: v for k, v in instances.items() if v['category'] != 'unknown'}
    
    print(f"Unknown instances: {len(unknown_instances)} ({sum(v['count'] for v in unknown_instances.values())} voxels)")
    print(f"Known instances: {len(known_instances)} ({sum(v['count'] for v in known_instances.values())} voxels)")
    
    # Add unknown voxels (in gray, subsampled)
    if show_unknown and unknown_instances:
        print(f"Adding 'unknown' voxels (subsampling 1/{subsample_unknown})...")
        for instance_id, data in unknown_instances.items():
            coords = data['coords'][::subsample_unknown]  # Subsampling
            
            if len(coords) > 0:
                fig.add_trace(go.Scatter3d(
                    x=coords[:, 0],
                    y=coords[:, 1],
                    z=coords[:, 2],
                    mode='markers',
                    name=f'Unknown (ID:{instance_id})',
                    marker=dict(
                        size=2,
                        color='rgb(80, 80, 80)',  # Dark gray, distinguishable from background
                        opacity=0.4,
                    ),
                    text=[f'Unknown<br>Instance: {instance_id}'] * len(coords),
                    hovertemplate='<b>%{text}</b><br>X: %{x:.2f}<br>Y: %{y:.2f}<br>Z: %{z:.2f}<extra></extra>',
                    showlegend=False
                ))
    
    # Add known instances (with colors and categories)
    print(f"Adding instances with known categories (subsampling 1/{subsample_known})...")
    category_colors = {}
    
    for instance_id, data in sorted(known_instances.items(), key=lambda x: x[1]['count'], reverse=True):
        category = data['category']
        coords = data['coords'][::subsample_known]  # Light subsampling
        colors = data['colors'][::subsample_known]
        
        if len(coords) == 0:
            continue
        
        # Use average color of the instance
        avg_color = np.mean(colors, axis=0).astype(int)
        color_str = f'rgb({avg_color[0]}, {avg_color[1]}, {avg_color[2]})'
        
        # Hover information
        hover_text = [
            f'<b>{category}</b><br>Instance ID: {instance_id}<br>Voxels: {data["count"]}'
        ] * len(coords)
        
        fig.add_trace(go.Scatter3d(
            x=coords[:, 0],
            y=coords[:, 1],
            z=coords[:, 2],
            mode='markers',
            name=f'{category} (ID:{instance_id})',
            marker=dict(
                size=3,
                color=color_str,
                opacity=0.8,
                line=dict(width=0)
            ),
            text=hover_text,
            hovertemplate='%{text}<br>X: %{x:.2f}<br>Y: %{y:.2f}<br>Z: %{z:.2f}<extra></extra>',
        ))
    
    # Configure layout
    total_voxels = len(vertices)
    num_instances = len(instances)
    
    fig.update_layout(
        title=dict(
            text=f'Voxeland Semantic Map<br><sub>{total_voxels:,} voxels | {num_instances} instances | Interactive 3D View</sub>',
            x=0.5,
            xanchor='center',
            font=dict(color='white')
        ),
        scene=dict(
            xaxis_title='X (m)',
            yaxis_title='Y (m)',
            zaxis_title='Z (m)',
            aspectmode='data',
            camera=dict(
                eye=dict(x=1.5, y=1.5, z=1.5)
            ),
            xaxis=dict(
                backgroundcolor='rgb(20, 20, 20)',
                gridcolor='rgb(60, 60, 60)',
                showbackground=True,
                zerolinecolor='rgb(80, 80, 80)',
                title=dict(font=dict(color='white')),
                tickfont=dict(color='white')
            ),
            yaxis=dict(
                backgroundcolor='rgb(20, 20, 20)',
                gridcolor='rgb(60, 60, 60)',
                showbackground=True,
                zerolinecolor='rgb(80, 80, 80)',
                title=dict(font=dict(color='white')),
                tickfont=dict(color='white')
            ),
            zaxis=dict(
                backgroundcolor='rgb(20, 20, 20)',
                gridcolor='rgb(60, 60, 60)',
                showbackground=True,
                zerolinecolor='rgb(80, 80, 80)',
                title=dict(font=dict(color='white')),
                tickfont=dict(color='white')
            ),
        ),
        width=1400,
        height=900,
        showlegend=True,
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01,
            bgcolor="rgba(30, 30, 30, 0.9)",
            bordercolor="rgb(60, 60, 60)",
            borderwidth=1,
            font=dict(color='white')
        ),
        hovermode='closest',
        paper_bgcolor='rgb(15, 15, 15)',
        plot_bgcolor='rgb(15, 15, 15)',
    )
    
    # Save or display
    if output_html:
        output_path = Path(output_html)
        print(f"\nSaving visualization to: {output_path}")
        fig.write_html(str(output_path))
        print(f"✓ File saved: {output_path}")
        print(f"  Open the file in your browser to view the interactive visualization")
    else:
        print("\nOpening visualization in browser...")
        fig.show()
    
    # Display statistics
    print("\n" + "="*60)
    print("MAP STATISTICS")
    print("="*60)
    
    category_stats = defaultdict(lambda: {'instances': 0, 'voxels': 0})
    for instance_id, data in instances.items():
        category = data['category']
        category_stats[category]['instances'] += 1
        category_stats[category]['voxels'] += data['count']
    
    print(f"\n{'Category':<20} {'Instances':>12} {'Voxels':>12}")
    print("-" * 60)
    for category in sorted(category_stats.keys()):
        stats = category_stats[category]
        print(f"{category:<20} {stats['instances']:>12} {stats['voxels']:>12,}")
    
    print("-" * 60)
    print(f"{'TOTAL':<20} {num_instances:>12} {total_voxels:>12,}")
    print("="*60)


def main():
    parser = argparse.ArgumentParser(
        description='Interactive 3D visualizer for Voxeland semantic maps',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Usage examples:
  # Visualize with default settings
  python3 visualize_voxeland_map.py
  
  # Specify PLY file and save as HTML
  python3 visualize_voxeland_map.py --ply /path/to/map.ply --output my_map.html
  
  # Hide unknown voxels for better performance
  python3 visualize_voxeland_map.py --no-unknown
  
  # Adjust subsampling for better performance
  python3 visualize_voxeland_map.py --subsample-unknown 20 --subsample-known 5
        """
    )
    
    # Get script directory for relative paths
    script_dir = Path(__file__).parent
    
    parser.add_argument(
        '--ply',
        type=str,
        default=str(script_dir / 'voxeland_semantic_map_auto.ply'),
        help='Path to Voxeland PLY file (default: voxeland_semantic_map_auto.ply in script directory)'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        default=str(script_dir / 'voxeland_map_3d.html'),
        help='Path to output HTML file (default: voxeland_map_3d.html in script directory)'
    )
    
    parser.add_argument(
        '--no-unknown',
        action='store_true',
        help='Do not show voxels with "unknown" category'
    )
    
    parser.add_argument(
        '--subsample-unknown',
        type=int,
        default=10,
        help='Subsampling factor for unknown voxels (default: 10, higher = faster)'
    )
    
    parser.add_argument(
        '--subsample-known',
        type=int,
        default=2,
        help='Subsampling factor for known categories (default: 2)'
    )
    
    args = parser.parse_args()
    
    # Check if file exists
    ply_path = Path(args.ply)
    if not ply_path.exists():
        print(f"ERROR: File not found: {ply_path}", file=sys.stderr)
        print(f"\nMake sure Voxeland is running and has generated the file.", file=sys.stderr)
        sys.exit(1)
    
    # Read PLY file
    try:
        ply_data = read_ply_file(ply_path)
    except Exception as e:
        print(f"ERROR reading PLY file: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Create visualization
    try:
        create_interactive_visualization(
            ply_data,
            output_html=args.output,
            show_unknown=not args.no_unknown,
            subsample_unknown=args.subsample_unknown,
            subsample_known=args.subsample_known
        )
    except Exception as e:
        print(f"ERROR creating visualization: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    print("\n✓ Visualization completed successfully!")


if __name__ == '__main__':
    main()
